In [10]:
# Show a few example clip IDs
print("Example clip IDs:")
for clip_id in df.index[:10]:
    print(f"  {clip_id}  ->  chunk={df.at[clip_id, 'chunk']}")

Example clip IDs:
  25cd4769-5dcf-4b53-a351-bf2c5deb6124  ->  chunk=0
  2edf278f-d5e3-4b83-b5df-923a04335725  ->  chunk=0
  eed514a0-a366-4550-b9bd-4c296c531511  ->  chunk=0
  ecafce84-447d-43a6-aff1-b385fbc71f15  ->  chunk=0
  1f47bf7f-d233-480c-b166-7512d8e9ac97  ->  chunk=0
  c6915a10-9f22-464d-a422-15b8960a57d7  ->  chunk=0
  ea5c5be6-5e18-4489-9784-8f73860f887b  ->  chunk=0
  1fcf2fef-279b-4490-adc6-9b7d1ff0118d  ->  chunk=0
  ef4264ed-0fd2-4a64-9831-87e1aae28407  ->  chunk=0
  30f3d243-f26e-43f9-a63a-ac5d1b115d15  ->  chunk=0

In [12]:
# Chunk distribution
if "chunk" in df.columns:
    print("Chunk value counts:")
    print(df["chunk"].value_counts().sort_index())
    print(f"\nTotal chunks: {df['chunk'].nunique()}")
    print(f"Clips per chunk (mean): {df['chunk'].value_counts().mean():.1f}")

Chunk value counts:
chunk
0       100
1       100
2        99
3       100
4       100
       ...
3141     97
3142     94
3143     79
3144     95
3145     73
Name: count, Length: 3146, dtype: int64

Total chunks: 3146
Clips per chunk (mean): 97.3

In [13]:
df.describe(include="all")

       clip_is_valid          chunk   split
count         306152  306152.000000  306152
unique             1            NaN       3
top             True            NaN   train
freq          306152            NaN  153625
mean             NaN    1567.497446     NaN
std              NaN     908.277175     NaN
min              NaN       0.000000     NaN
25%              NaN     782.000000     NaN
50%              NaN    1559.000000     NaN
75%              NaN    2361.000000     NaN
max              NaN    3145.000000     NaN

In [14]:
print("Columns:", df.columns.tolist())
print("\nDtypes:")
print(df.dtypes)
print("\nNull counts:")
print(df.isnull().sum())

Columns: ['clip_is_valid', 'chunk', 'split']

Dtypes:
clip_is_valid     bool
chunk            int64
split              str
dtype: object

Null counts:
clip_is_valid    0
chunk            0
split            0
dtype: int64

In [15]:
import pandas as pd

df = pd.read_parquet("/home/duzl/hlc/physical_ai_av_usage/clip_index.parquet")
print(f"Shape: {df.shape}")
print(f"Index name: {df.index.name}")
df.head(10)

Shape: (306152, 3)
Index name: clip_id

                                      clip_is_valid  chunk  split
clip_id
25cd4769-5dcf-4b53-a351-bf2c5deb6124           True      0  train
2edf278f-d5e3-4b83-b5df-923a04335725           True      0  train
eed514a0-a366-4550-b9bd-4c296c531511           True      0  train
ecafce84-447d-43a6-aff1-b385fbc71f15           True      0  train
1f47bf7f-d233-480c-b166-7512d8e9ac97           True      0  train
c6915a10-9f22-464d-a422-15b8960a57d7           True      0  train
ea5c5be6-5e18-4489-9784-8f73860f887b           True      0  train
1fcf2fef-279b-4490-adc6-9b7d1ff0118d           True      0  train
ef4264ed-0fd2-4a64-9831-87e1aae28407           True      0  train
30f3d243-f26e-43f9-a63a-ac5d1b115d15           True      0  train

# Explore clip_index.parquet

In [11]:
# Analyze split column distribution
if "split" in df.columns:
    print("Split value counts:")
    split_counts = df["split"].value_counts()
    print(split_counts)
    
    print("\nSplit percentages:")
    split_percentages = df["split"].value_counts(normalize=True) * 100
    for split, pct in split_percentages.items():
        print(f"  {split}: {pct:.2f}%")
    
    # Cross-tabulation: split vs chunk
    print("\nSplit vs Chunk cross-tabulation:")
    print(pd.crosstab(df["split"], df["chunk"], margins=True))
else:
    print("No 'split' column found in the dataset")

Split value counts:
split
train    153625
val       90928
test      61599
Name: count, dtype: int64

Split percentages:
  train: 50.18%
  val: 29.70%
  test: 20.12%

Split vs Chunk cross-tabulation:
chunk    0    1   2    3    4    5   6   7    8   9  ...  3137  3138  3139  \
split                                                ...
test     0    0   0    0    0    0   0   0    0   0  ...     0     0     0
train  100  100  99  100  100  100  99  99  100  99  ...    91    87    91
val      0    0   0    0    0    0   0   0    0   0  ...     0     0     0
All    100  100  99  100  100  100  99  99  100  99  ...    91    87    91

chunk  3140  3141  3142  3143  3144  3145     All
split
test      0     0     0     0    95    73   61599
train    77     0     0     0     0     0  153625
val       0    97    94    79     0     0   90928
All      77    97    94    79    95    73  306152

[4 rows x 3147 columns]
chunk    0    1   2    3    4    5   6   7    8   9  ...  3137  3138  3139  \
split                                                ...
test     0    0   0    0    0    0   0   0    0   0  ...     0     0     0
train  100  100  99  100  100  100  99  99  100  99  ...    91    87    91
val      0    0   0    0    0    0   0   0    0   0  ...     0     0     0
All    100  100  99  100  100  100  99  99  100  99  ...    91    87    91

chunk  3140  3141  3142  3143  3144  3145     All
split
test      0     0     0     0    95    73   61599
train    77     0     0     0     0     0  153625
val       0    97    94    79     0     0   90928
All      77    97    94    79    95    73  306152

[4 rows x 3147 columns]